import "./globals.css";
import { Work_Sans } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster"

const workSans = Work_Sans({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'] ,// Add the weights you need
  variable: '--font-work-sans'
});

export const metadata = {
  title: "AI Notes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={workSans.variable}>
      <body className="antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
